alias zshconfig="nvim ~/.zshrc"
alias c='clear'
alias nf='fastfetch'
alias pf='fastfetch'
alias neofetch='fastfetch'
alias ff='fastfetch'
alias ls='eza -a --icons=always'
alias ll='eza -al --icons=always'
alias lt='eza -a --tree --level=1 --icons=always'
alias shutdown='systemctl poweroff'
alias v='$EDITOR'
#alias vim='$EDITOR'
alias get='sudo pacman -S'
alias gety='yay -S'
alias kick='sudo pacman -R'
alias update='sudo pacman -Syu'
alias yayu='yay -Syu'
alias orphan='sudo pacman -Rns $(pacman -Qtdq)'
alias sql='mariadb -u ganesh -p3053'
alias anime='ani-cli'
alias y='yazi'
alias off='shutdown'
alias grub-config='sudo nvim /etc/default/grub'
alias grub-update='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias alias-config='vim /home/jkhill/.zsh/modules/aliases.zsh'
alias pacfind='pacman -Q | grep'
alias cmdhis='cat ~/.zsh_history | grep'
alias flexing='echo i use arch btw | figlet | lolcat'
